[project]
name = 'stack-yield'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []

[networks.testnet]
node_rpc_address = "https://stacks-node-api.testnet.stacks.co"
deployment_fee_rate = 10

[contracts.rewards-ledger]
path = 'contracts/rewards-ledger.clar'
clarity_version = 3
epoch = 'latest'

[contracts.stacking-pool]
path = 'contracts/stacking-pool.clar'
clarity_version = 3
epoch = 'latest'

[contracts.swap-manager]
path = 'contracts/swap-manager.clar'
clarity_version = 3
epoch = 'latest'

[contracts.vault]
path = 'contracts/vault.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
